import type { TranslationKeys } from "./en";

const es: TranslationKeys = {
  nav: { dashboard: "Panel", quotes: "Presupuestos", invoices: "Facturas", customers: "Clientes", billing: "Facturación", settings: "Configuración", logOut: "Cerrar sesión" },
  dashboard: { title: "Panel", welcomeBack: "Bienvenido de nuevo", totalQuotes: "Total presupuestos", totalInvoices: "Total facturas", acceptedQuotes: "Presupuestos aceptados", acceptanceRate: "tasa de aceptación", revenue: "Ingresos", fromPaidInvoices: "de facturas pagadas", newQuote: "Nuevo presupuesto", newInvoice: "Nueva factura", addCustomer: "Añadir cliente", createNewQuote: "Crear nuevo presupuesto", createNewInvoice: "Crear nueva factura", addNewCustomer: "Añadir nuevo cliente", recentQuotes: "Presupuestos recientes", recentInvoices: "Facturas recientes", viewAll: "Ver todo", noQuotesYet: "Sin presupuestos", noInvoicesYet: "Sin facturas", noCustomer: "Sin cliente" },
  quotes: { title: "Presupuestos", subtitle: "Gestiona tus presupuestos y propuestas.", newQuote: "Nuevo presupuesto", createQuote: "Crear presupuesto", noQuotesYet: "Sin presupuestos", noQuotesDesc: "Crea tu primer presupuesto.", searchQuotes: "Buscar presupuestos...", quote: "Presupuesto", customer: "Cliente", date: "Fecha", amount: "Importe", status: "Estado", actions: "Acciones", send: "Enviar", accept: "Aceptar", convert: "Convertir", createNewQuote: "Crear un nuevo presupuesto para tu cliente.", quoteDate: "Fecha presupuesto", expiryDate: "Fecha vencimiento", projectDescription: "Descripción del proyecto", describeProject: "Describe el proyecto...", lineItems: "Líneas", addItem: "Añadir línea", itemName: "Nombre artículo", description: "Descripción", qty: "Cant.", unitPrice: "Precio unitario", lineTotal: "Total línea", notesAndTerms: "Notas y condiciones", notes: "Notas", additionalNotes: "Notas adicionales...", termsAndConditions: "Términos y condiciones", terms: "Condiciones...", summary: "Resumen", tax: "Impuesto", taxRate: "Tasa impositiva (%)", discount: "Descuento ($)", subtotal: "Subtotal", total: "Total", saveDraft: "Guardar borrador", sendQuote: "Enviar presupuesto", saving: "Guardando...", editQuote: "Editar presupuesto", downloadPDF: "Descargar PDF", markAccepted: "Marcar aceptado", markRejected: "Marcar rechazado", convertToInvoice: "Convertir a factura", quoteNotFound: "Presupuesto no encontrado.", backToQuotes: "Volver a presupuestos", details: "Detalles", email: "Email", issueDate: "Fecha emisión", item: "Artículo", price: "Precio", preview: "Vista previa", template: "Plantilla", selectTemplate: "Seleccionar plantilla" },
  invoices: { title: "Facturas", subtitle: "Gestiona tus facturas y pagos.", newInvoice: "Nueva factura", createInvoice: "Crear factura", noInvoicesYet: "Sin facturas", noInvoicesDesc: "Crea tu primera factura.", searchInvoices: "Buscar facturas...", invoice: "Factura", customer: "Cliente", date: "Fecha", due: "Vence", amount: "Importe", status: "Estado", actions: "Acciones", markSent: "Marcar enviada", markPaid: "Marcar pagada", createNewInvoice: "Crear nueva factura para tu cliente.", issueDate: "Fecha emisión", dueDate: "Fecha vencimiento", lineItems: "Líneas", addItem: "Añadir línea", itemName: "Nombre artículo", description: "Descripción", qty: "Cant.", unitPrice: "Precio unitario", lineTotal: "Total línea", notes: "Notas", additionalNotes: "Notas adicionales...", summary: "Resumen", tax: "Impuesto", taxRate: "Tasa impositiva (%)", discount: "Descuento ($)", subtotal: "Subtotal", total: "Total", saveDraft: "Guardar borrador", saveAndSend: "Guardar y enviar", saving: "Guardando...", editInvoice: "Editar factura", downloadPDF: "Descargar PDF", invoiceNotFound: "Factura no encontrada.", backToInvoices: "Volver a facturas", details: "Detalles", email: "Email", item: "Artículo", price: "Precio", preview: "Vista previa", template: "Plantilla", selectTemplate: "Seleccionar plantilla" },
  customers: { title: "Clientes", subtitle: "Gestiona tus contactos de clientes.", addCustomer: "Añadir cliente", noCustomersYet: "Sin clientes", noCustomersDesc: "Añade tu primer cliente.", searchCustomers: "Buscar clientes...", addNewCustomer: "Añadir nuevo cliente.", fullName: "Nombre completo", email: "Email", phone: "Teléfono", address: "Dirección", companyName: "Empresa (opcional)", notes: "Notas", additionalNotes: "Notas adicionales...", saveCustomer: "Guardar cliente", cancel: "Cancelar", saving: "Guardando..." },
  settings: { title: "Configuración", subtitle: "Gestiona tu cuenta y empresa.", profile: "Perfil", company: "Empresa", branding: "Marca", language: "Idioma", templates: "Plantillas", profileInfo: "Información de perfil", fullName: "Nombre completo", email: "Email", phone: "Teléfono", saveChanges: "Guardar cambios", companyDetails: "Datos de empresa", companyNameLabel: "Nombre empresa", orgNumber: "Número de organización", address: "Dirección", website: "Sitio web", logo: "Logo", uploadLogo: "Subir logo", changeLogo: "Cambiar", removeLogo: "Eliminar", brandingTitle: "Marca", primaryColor: "Color primario", secondaryColor: "Color secundario", footerText: "Texto pie de página", languageTitle: "Idioma", appLanguage: "Idioma de la aplicación", appLanguageDesc: "Elige el idioma de la interfaz.", documentLanguage: "Idioma de documentos", documentLanguageDesc: "Idioma predeterminado para presupuestos y facturas.", templatesTitle: "Plantillas de documentos", defaultQuoteTemplate: "Plantilla de presupuesto", defaultInvoiceTemplate: "Plantilla de factura", saved: "Configuración guardada" },
  status: { draft: "Borrador", sent: "Enviado", accepted: "Aceptado", rejected: "Rechazado", paid: "Pagado", overdue: "Vencido" },
  templates: { minimal: "Mínimo", classic: "Clásico", bold: "Moderno audaz", elegant: "Elegante", compact: "Compacto profesional" },
  common: { save: "Guardar", cancel: "Cancelar", delete: "Eliminar", edit: "Editar", back: "Volver", loading: "Cargando...", noData: "—", selectCustomer: "Seleccionar cliente", item: "Artículo" },
  billing: { title: "Facturación", subtitle: "Gestiona tu suscripción.", currentPlan: "Plan actual", manageSubscription: "Gestionar suscripción", usageThisPeriod: "Uso este período", quotesCreated: "Presupuestos creados", invoicesCreated: "Facturas creadas", customers: "Clientes", unlimited: "Ilimitado", unlimitedOnPro: "Ilimitado en Pro", availablePlans: "Planes disponibles", downgrade: "Bajar plan", upgrade: "Subir plan" },
  languages: { en: "English", sv: "Svenska", de: "Deutsch", es: "Español", fr: "Français", zh: "中文", pt: "Português" },
};

export default es;
