import type { TranslationKeys } from "./en";

const pt: TranslationKeys = {
  nav: { dashboard: "Painel", quotes: "Orçamentos", invoices: "Faturas", customers: "Clientes", billing: "Faturação", settings: "Configurações", logOut: "Sair" },
  dashboard: { title: "Painel", welcomeBack: "Bem-vindo de volta", totalQuotes: "Total orçamentos", totalInvoices: "Total faturas", acceptedQuotes: "Orçamentos aceitos", acceptanceRate: "taxa de aceitação", revenue: "Receita", fromPaidInvoices: "de faturas pagas", newQuote: "Novo orçamento", newInvoice: "Nova fatura", addCustomer: "Adicionar cliente", createNewQuote: "Criar novo orçamento", createNewInvoice: "Criar nova fatura", addNewCustomer: "Adicionar novo cliente", recentQuotes: "Orçamentos recentes", recentInvoices: "Faturas recentes", viewAll: "Ver tudo", noQuotesYet: "Sem orçamentos", noInvoicesYet: "Sem faturas", noCustomer: "Sem cliente" },
  quotes: { title: "Orçamentos", subtitle: "Gerencie seus orçamentos e propostas.", newQuote: "Novo orçamento", createQuote: "Criar orçamento", noQuotesYet: "Sem orçamentos", noQuotesDesc: "Crie seu primeiro orçamento.", searchQuotes: "Buscar orçamentos...", quote: "Orçamento", customer: "Cliente", date: "Data", amount: "Valor", status: "Status", actions: "Ações", send: "Enviar", accept: "Aceitar", convert: "Converter", createNewQuote: "Criar novo orçamento para seu cliente.", quoteDate: "Data do orçamento", expiryDate: "Data de validade", projectDescription: "Descrição do projeto", describeProject: "Descreva o projeto...", lineItems: "Itens", addItem: "Adicionar item", itemName: "Nome do item", description: "Descrição", qty: "Qtd", unitPrice: "Preço unitário", lineTotal: "Total linha", notesAndTerms: "Notas e termos", notes: "Notas", additionalNotes: "Notas adicionais...", termsAndConditions: "Termos e condições", terms: "Termos...", summary: "Resumo", tax: "Imposto", taxRate: "Taxa de imposto (%)", discount: "Desconto ($)", subtotal: "Subtotal", total: "Total", saveDraft: "Salvar rascunho", sendQuote: "Enviar orçamento", saving: "Salvando...", editQuote: "Editar orçamento", downloadPDF: "Baixar PDF", markAccepted: "Marcar aceito", markRejected: "Marcar rejeitado", convertToInvoice: "Converter em fatura", quoteNotFound: "Orçamento não encontrado.", backToQuotes: "Voltar aos orçamentos", details: "Detalhes", email: "Email", issueDate: "Data de emissão", item: "Item", price: "Preço", preview: "Pré-visualizar", template: "Modelo", selectTemplate: "Selecionar modelo" },
  invoices: { title: "Faturas", subtitle: "Gerencie suas faturas e pagamentos.", newInvoice: "Nova fatura", createInvoice: "Criar fatura", noInvoicesYet: "Sem faturas", noInvoicesDesc: "Crie sua primeira fatura.", searchInvoices: "Buscar faturas...", invoice: "Fatura", customer: "Cliente", date: "Data", due: "Vencimento", amount: "Valor", status: "Status", actions: "Ações", markSent: "Marcar enviada", markPaid: "Marcar paga", createNewInvoice: "Criar nova fatura para seu cliente.", issueDate: "Data de emissão", dueDate: "Data de vencimento", lineItems: "Itens", addItem: "Adicionar item", itemName: "Nome do item", description: "Descrição", qty: "Qtd", unitPrice: "Preço unitário", lineTotal: "Total linha", notes: "Notas", additionalNotes: "Notas adicionais...", summary: "Resumo", tax: "Imposto", taxRate: "Taxa de imposto (%)", discount: "Desconto ($)", subtotal: "Subtotal", total: "Total", saveDraft: "Salvar rascunho", saveAndSend: "Salvar e enviar", saving: "Salvando...", editInvoice: "Editar fatura", downloadPDF: "Baixar PDF", invoiceNotFound: "Fatura não encontrada.", backToInvoices: "Voltar às faturas", details: "Detalhes", email: "Email", item: "Item", price: "Preço", preview: "Pré-visualizar", template: "Modelo", selectTemplate: "Selecionar modelo" },
  customers: { title: "Clientes", subtitle: "Gerencie seus contatos de clientes.", addCustomer: "Adicionar cliente", noCustomersYet: "Sem clientes", noCustomersDesc: "Adicione seu primeiro cliente.", searchCustomers: "Buscar clientes...", addNewCustomer: "Adicionar novo cliente.", fullName: "Nome completo", email: "Email", phone: "Telefone", address: "Endereço", companyName: "Empresa (opcional)", notes: "Notas", additionalNotes: "Notas adicionais...", saveCustomer: "Salvar cliente", cancel: "Cancelar", saving: "Salvando..." },
  settings: { title: "Configurações", subtitle: "Gerencie sua conta e empresa.", profile: "Perfil", company: "Empresa", branding: "Marca", language: "Idioma", templates: "Modelos", profileInfo: "Informações do perfil", fullName: "Nome completo", email: "Email", phone: "Telefone", saveChanges: "Salvar alterações", companyDetails: "Dados da empresa", companyNameLabel: "Nome da empresa", orgNumber: "Número de organização", address: "Endereço", website: "Website", logo: "Logo", uploadLogo: "Enviar logo", changeLogo: "Alterar", removeLogo: "Remover", brandingTitle: "Marca", primaryColor: "Cor primária", secondaryColor: "Cor secundária", footerText: "Texto rodapé padrão", languageTitle: "Idioma", appLanguage: "Idioma do aplicativo", appLanguageDesc: "Escolha o idioma da interface.", documentLanguage: "Idioma dos documentos", documentLanguageDesc: "Idioma padrão para orçamentos e faturas.", templatesTitle: "Modelos de documentos", defaultQuoteTemplate: "Modelo de orçamento padrão", defaultInvoiceTemplate: "Modelo de fatura padrão", saved: "Configurações salvas" },
  status: { draft: "Rascunho", sent: "Enviado", accepted: "Aceito", rejected: "Rejeitado", paid: "Pago", overdue: "Atrasado" },
  templates: { minimal: "Mínimo", classic: "Clássico", bold: "Moderno ousado", elegant: "Elegante", compact: "Compacto profissional" },
  common: { save: "Salvar", cancel: "Cancelar", delete: "Excluir", edit: "Editar", back: "Voltar", loading: "Carregando...", noData: "—", selectCustomer: "Selecionar cliente", item: "Item" },
  billing: { title: "Faturação", subtitle: "Gerencie sua assinatura.", currentPlan: "Plano atual", manageSubscription: "Gerenciar assinatura", usageThisPeriod: "Uso neste período", quotesCreated: "Orçamentos criados", invoicesCreated: "Faturas criadas", customers: "Clientes", unlimited: "Ilimitado", unlimitedOnPro: "Ilimitado no Pro", availablePlans: "Planos disponíveis", downgrade: "Reduzir plano", upgrade: "Atualizar plano" },
  languages: { en: "English", sv: "Svenska", de: "Deutsch", es: "Español", fr: "Français", zh: "中文", pt: "Português" },
};

export default pt;
