import type { TranslationKeys } from "./en";

const zh: TranslationKeys = {
  nav: { dashboard: "仪表板", quotes: "报价", invoices: "发票", customers: "客户", billing: "账单", settings: "设置", logOut: "退出" },
  dashboard: { title: "仪表板", welcomeBack: "欢迎回来", totalQuotes: "报价总数", totalInvoices: "发票总数", acceptedQuotes: "已接受报价", acceptanceRate: "接受率", revenue: "收入", fromPaidInvoices: "来自已付发票", newQuote: "新报价", newInvoice: "新发票", addCustomer: "添加客户", createNewQuote: "创建新报价", createNewInvoice: "创建新发票", addNewCustomer: "添加新客户", recentQuotes: "最近报价", recentInvoices: "最近发票", viewAll: "查看全部", noQuotesYet: "暂无报价", noInvoicesYet: "暂无发票", noCustomer: "无客户" },
  quotes: { title: "报价", subtitle: "管理你的报价和提案。", newQuote: "新报价", createQuote: "创建报价", noQuotesYet: "暂无报价", noQuotesDesc: "创建你的第一个报价。", searchQuotes: "搜索报价...", quote: "报价", customer: "客户", date: "日期", amount: "金额", status: "状态", actions: "操作", send: "发送", accept: "接受", convert: "转换", createNewQuote: "为客户创建新报价。", quoteDate: "报价日期", expiryDate: "到期日", projectDescription: "项目描述", describeProject: "描述项目...", lineItems: "行项目", addItem: "添加项目", itemName: "项目名称", description: "描述", qty: "数量", unitPrice: "单价", lineTotal: "行合计", notesAndTerms: "备注与条款", notes: "备注", additionalNotes: "附加备注...", termsAndConditions: "条款与条件", terms: "条款...", summary: "摘要", tax: "税", taxRate: "税率 (%)", discount: "折扣 ($)", subtotal: "小计", total: "合计", saveDraft: "保存草稿", sendQuote: "发送报价", saving: "保存中...", editQuote: "编辑报价", downloadPDF: "下载PDF", markAccepted: "标记为已接受", markRejected: "标记为已拒绝", convertToInvoice: "转换为发票", quoteNotFound: "报价未找到。", backToQuotes: "返回报价", details: "详情", email: "邮箱", issueDate: "签发日期", item: "项目", price: "价格", preview: "预览", template: "模板", selectTemplate: "选择模板" },
  invoices: { title: "发票", subtitle: "管理你的发票和付款。", newInvoice: "新发票", createInvoice: "创建发票", noInvoicesYet: "暂无发票", noInvoicesDesc: "创建你的第一张发票。", searchInvoices: "搜索发票...", invoice: "发票", customer: "客户", date: "日期", due: "到期", amount: "金额", status: "状态", actions: "操作", markSent: "标记已发送", markPaid: "标记已付", createNewInvoice: "为客户创建新发票。", issueDate: "签发日期", dueDate: "到期日", lineItems: "行项目", addItem: "添加项目", itemName: "项目名称", description: "描述", qty: "数量", unitPrice: "单价", lineTotal: "行合计", notes: "备注", additionalNotes: "附加备注...", summary: "摘要", tax: "税", taxRate: "税率 (%)", discount: "折扣 ($)", subtotal: "小计", total: "合计", saveDraft: "保存草稿", saveAndSend: "保存并发送", saving: "保存中...", editInvoice: "编辑发票", downloadPDF: "下载PDF", invoiceNotFound: "发票未找到。", backToInvoices: "返回发票", details: "详情", email: "邮箱", item: "项目", price: "价格", preview: "预览", template: "模板", selectTemplate: "选择模板" },
  customers: { title: "客户", subtitle: "管理你的客户联系人。", addCustomer: "添加客户", noCustomersYet: "暂无客户", noCustomersDesc: "添加你的第一个客户。", searchCustomers: "搜索客户...", addNewCustomer: "添加新客户。", fullName: "全名", email: "邮箱", phone: "电话", address: "地址", companyName: "公司名称（可选）", notes: "备注", additionalNotes: "附加备注...", saveCustomer: "保存客户", cancel: "取消", saving: "保存中..." },
  settings: { title: "设置", subtitle: "管理你的账户和公司设置。", profile: "个人资料", company: "公司", branding: "品牌", language: "语言", templates: "模板", profileInfo: "个人信息", fullName: "全名", email: "邮箱", phone: "电话", saveChanges: "保存更改", companyDetails: "公司详情", companyNameLabel: "公司名称", orgNumber: "组织号", address: "地址", website: "网站", logo: "标志", uploadLogo: "上传标志", changeLogo: "更改", removeLogo: "移除", brandingTitle: "品牌", primaryColor: "主色", secondaryColor: "辅色", footerText: "默认页脚文字", languageTitle: "语言", appLanguage: "应用语言", appLanguageDesc: "选择界面语言。", documentLanguage: "文档语言", documentLanguageDesc: "报价和发票的默认语言。", templatesTitle: "文档模板", defaultQuoteTemplate: "默认报价模板", defaultInvoiceTemplate: "默认发票模板", saved: "设置已保存" },
  status: { draft: "草稿", sent: "已发送", accepted: "已接受", rejected: "已拒绝", paid: "已付", overdue: "逾期" },
  templates: { minimal: "极简", classic: "经典", bold: "粗体现代", elegant: "优雅", compact: "紧凑专业" },
  common: { save: "保存", cancel: "取消", delete: "删除", edit: "编辑", back: "返回", loading: "加载中...", noData: "—", selectCustomer: "选择客户", item: "项目" },
  billing: { title: "账单", subtitle: "管理你的订阅。", currentPlan: "当前计划", manageSubscription: "管理订阅", usageThisPeriod: "本期使用量", quotesCreated: "创建的报价", invoicesCreated: "创建的发票", customers: "客户", unlimited: "无限", unlimitedOnPro: "Pro无限", availablePlans: "可用计划", downgrade: "降级", upgrade: "升级" },
  languages: { en: "English", sv: "Svenska", de: "Deutsch", es: "Español", fr: "Français", zh: "中文", pt: "Português" },
};

export default zh;
