import type { TranslationKeys } from "./en";

const zh: TranslationKeys = {
  nav: { dashboard: "仪表板", quotes: "报价", invoices: "发票", customers: "客户", billing: "账单", settings: "设置", logOut: "退出" },
  dashboard: { title: "仪表板", welcomeBack: "欢迎回来", totalQuotes: "报价总数", totalInvoices: "发票总数", acceptedQuotes: "已接受报价", acceptanceRate: "接受率", revenue: "收入", fromPaidInvoices: "来自已付发票", newQuote: "新报价", newInvoice: "新发票", addCustomer: "添加客户", createNewQuote: "创建新报价", createNewInvoice: "创建新发票", addNewCustomer: "添加新客户", recentQuotes: "最近报价", recentInvoices: "最近发票", viewAll: "查看全部", noQuotesYet: "暂无报价", noInvoicesYet: "暂无发票", noCustomer: "无客户" },
  quotes: { title: "报价", subtitle: "管理你的报价和提案。", newQuote: "新报价", createQuote: "创建报价", noQuotesYet: "暂无报价", noQuotesDesc: "创建你的第一个报价。", searchQuotes: "搜索报价...", quote: "报价", customer: "客户", date: "日期", amount: "金额", status: "状态", actions: "操作", send: "发送", accept: "接受", convert: "转换", createNewQuote: "为客户创建新报价。", quoteDate: "报价日期", expiryDate: "到期日", projectDescription: "项目描述", describeProject: "描述项目...", lineItems: "行项目", addItem: "添加项目", itemName: "项目名称", description: "描述", qty: "数量", unitPrice: "单价", lineTotal: "行合计", notesAndTerms: "备注与条款", notes: "备注", additionalNotes: "附加备注...", termsAndConditions: "条款与条件", terms: "条款...", summary: "摘要", tax: "税", taxRate: "税率 (%)", discount: "折扣 ($)", subtotal: "小计", total: "合计", saveDraft: "保存草稿", sendQuote: "发送报价", saving: "保存中...", editQuote: "编辑报价", downloadPDF: "下载PDF", markAccepted: "标记为已接受", markRejected: "标记为已拒绝", convertToInvoice: "转换为发票", quoteNotFound: "报价未找到。", backToQuotes: "返回报价", details: "详情", email: "邮箱", issueDate: "签发日期", item: "项目", price: "价格", preview: "预览", template: "模板", selectTemplate: "选择模板", markedAs: "已标记为", quoteUpdated: "报价已更新", updateDetails: "更新报价详情和行项目。", addAtLeastOneItem: "至少添加一个行项目" },
  invoices: { title: "发票", subtitle: "管理你的发票和付款。", newInvoice: "新发票", createInvoice: "创建发票", noInvoicesYet: "暂无发票", noInvoicesDesc: "创建你的第一张发票。", searchInvoices: "搜索发票...", invoice: "发票", customer: "客户", date: "日期", due: "到期", amount: "金额", status: "状态", actions: "操作", markSent: "标记已发送", markPaid: "标记已付", createNewInvoice: "为客户创建新发票。", issueDate: "签发日期", dueDate: "到期日", lineItems: "行项目", addItem: "添加项目", itemName: "项目名称", description: "描述", qty: "数量", unitPrice: "单价", lineTotal: "行合计", notes: "备注", additionalNotes: "附加备注...", summary: "摘要", tax: "税", taxRate: "税率 (%)", discount: "折扣 ($)", subtotal: "小计", total: "合计", saveDraft: "保存草稿", saveAndSend: "保存并发送", saving: "保存中...", editInvoice: "编辑发票", downloadPDF: "下载PDF", invoiceNotFound: "发票未找到。", backToInvoices: "返回发票", details: "详情", email: "邮箱", item: "项目", price: "价格", preview: "预览", template: "模板", selectTemplate: "选择模板", markedAs: "已标记为", invoiceUpdated: "发票已更新", updateDetails: "更新发票详情和行项目。", addAtLeastOneItem: "至少添加一个行项目", invoiceCreated: "发票已创建", failedToConvert: "转换失败" },
  customers: { title: "客户", subtitle: "管理你的客户联系人。", addCustomer: "添加客户", noCustomersYet: "暂无客户", noCustomersDesc: "添加你的第一个客户。", searchCustomers: "搜索客户...", addNewCustomer: "添加新客户。", fullName: "全名", email: "邮箱", phone: "电话", address: "地址", companyName: "公司名称（可选）", notes: "备注", additionalNotes: "附加备注...", saveCustomer: "保存客户", cancel: "取消", saving: "保存中...", nameRequired: "名称为必填项", customerAdded: "客户已添加" },
  settings: { title: "设置", subtitle: "管理你的账户和公司设置。", profile: "个人资料", company: "公司", branding: "品牌", language: "语言", templates: "模板", profileInfo: "个人信息", profileDesc: "您的个人详情", fullName: "全名", email: "邮箱", phone: "电话", saveChanges: "保存更改", companyDetails: "公司详情", companyDesc: "显示在您的报价和发票上", companyNameLabel: "公司名称", orgNumber: "组织号", address: "地址", website: "网站", logo: "标志", uploadLogo: "上传标志", changeLogo: "更改", removeLogo: "移除", uploadFailed: "上传失败", brandingTitle: "品牌", brandingDesc: "控制文档颜色", primaryColor: "主色", secondaryColor: "辅色", footerText: "默认页脚文字", livePreview: "实时预览", languageTitle: "语言", appLanguage: "应用语言", appLanguageDesc: "选择界面语言。", documentLanguage: "文档语言", documentLanguageDesc: "报价和发票的默认语言。", templatesTitle: "文档模板", defaultQuoteTemplate: "默认报价模板", defaultInvoiceTemplate: "默认发票模板", templateUsedFor: "用于创建新的", saved: "设置已保存" },
  status: { draft: "草稿", sent: "已发送", accepted: "已接受", rejected: "已拒绝", paid: "已付", overdue: "逾期" },
  templates: { minimal: "极简", classic: "经典", bold: "粗体现代", elegant: "优雅", compact: "紧凑专业" },
  templateDesc: { minimal: "干净通透的布局", classic: "传统衬线风格", bold: "渐变头部装饰", elegant: "居中精致风格", compact: "紧凑节省空间" },
  common: { save: "保存", cancel: "取消", delete: "删除", edit: "编辑", back: "返回", loading: "加载中...", noData: "—", selectCustomer: "选择客户", item: "项目" },
  billing: { title: "账单", subtitle: "管理你的订阅。", currentPlan: "当前计划", manageSubscription: "管理订阅", usageThisPeriod: "本期使用量", quotesCreated: "创建的报价", invoicesCreated: "创建的发票", customers: "客户", unlimited: "无限", unlimitedOnPro: "Pro无限", availablePlans: "可用计划", downgrade: "降级", upgrade: "升级" },
  languages: { en: "English", sv: "Svenska", de: "Deutsch", es: "Español", fr: "Français", zh: "中文", pt: "Português" },
  landing: { badge: "专为承包商和服务企业打造", heroTitle1: "创建专业报价", heroTitle2: "和发票", heroTitle3: "只需几秒。", heroDesc: "QuoteCraft帮助承包商和服务企业创建专业报价、发送发票并赢得更多业务——减少行政工作。", startFree: "免费开始", viewPricing: "查看价格", featuresTitle: "报价管理所需的一切", featuresDesc: "简单强大的工具，让您专注于业务——而非文书工作。", feat1Title: "专业报价", feat1Desc: "几秒钟内创建精美的品牌报价。添加行项目、税费、折扣并即时发送给客户。", feat2Title: "轻松收款的发票", feat2Desc: "一键将已接受的报价转换为发票。跟踪付款状态并发送提醒。", feat3Title: "客户管理", feat3Desc: "保持所有客户详细信息井然有序。自动填充报价和发票中的已保存信息。", feat4Title: "闪电般快速", feat4Desc: "为速度而生。在60秒内创建完整报价。无臃肿，无复杂。", howTitle: "如何使用", howDesc: "几分钟内即可上手。无需培训。", step1Title: "添加您的客户", step1Desc: "导入或一次性添加客户详细信息。在所有文档中重复使用。", step2Title: "创建报价", step2Desc: "添加行项目，设置条款，预览您的专业报价。", step3Title: "发送并获得接受", step3Desc: "与客户分享链接。他们可以在线查看和接受。", step4Title: "转换为发票", step4Desc: "一键将已接受的报价转换为可发送的发票。", pricingTitle: "简单透明的定价", pricingDesc: "免费开始。随业务增长升级。无隐藏费用。", mostPopular: "最受欢迎", starterName: "入门版", starterDesc: "适合刚起步的个体承包商。", starterF1: "每月最多10个报价", starterF2: "基本PDF导出", starterF3: "客户管理", starterF4: "邮件支持", proName: "专业版", proDesc: "适合需要更多功能的成长型企业。", proF1: "无限报价", proF2: "发票和转换功能", proF3: "自定义品牌", proF4: "优先支持", proF5: "可分享链接", businessName: "商业版", businessDesc: "为准备扩展的团队打造。", businessF1: "包含专业版所有功能", businessF2: "团队账户（即将推出）", businessF3: "未来集成", businessF4: "优先支持", businessF5: "API访问（即将推出）", ctaTitle: "准备好优化您的报价流程了吗？", ctaDesc: "成千上万的承包商每周通过QuoteCraft节省数小时。", ctaButton: "免费开始使用", navFeatures: "功能", navHowItWorks: "如何使用", navPricing: "价格", logIn: "登录", perMonth: "/月" },
  auth: { welcomeBack: "欢迎回来", loginDesc: "登录您的账户以继续。", email: "邮箱", password: "密码", forgotPassword: "忘记密码？", logIn: "登录", loggingIn: "登录中...", noAccount: "没有账户？", signUp: "注册", createAccount: "创建您的账户", createAccountDesc: "免费开始使用QuoteCraft。", fullName: "全名", createAccountBtn: "创建账户", creatingAccount: "创建中...", hasAccount: "已有账户？", accountCreated: "账户已创建！请查看邮箱确认。", passwordMinLength: "密码至少8个字符", resetPassword: "重置密码", resetDesc: "输入您的邮箱，我们将发送重置链接。", sendResetLink: "发送重置链接", sending: "发送中...", backToLogin: "返回登录", checkEmail: "查看您的邮箱", resetLinkSent: "我们已发送重置链接到", setNewPassword: "设置新密码", newPasswordDesc: "在下方输入新密码。", newPassword: "新密码", updatePassword: "更新密码", updating: "更新中...", passwordUpdated: "密码已更新", passwordUpdatedDesc: "您的密码已成功重置。", goToDashboard: "前往仪表板", loginHeroTitle: "从报价到发票\n只需几秒。", loginHeroDesc: "管理报价流程最简单的方式。", signupHeroTitle: "赢得更多业务\n减少行政工作。", signupHeroDesc: "创建免费账户，几分钟内发送第一份报价。" },
  docLabels: { quoteTo: "报价给", billTo: "发票给", issueDate: "签发日期", dueDate: "到期日", expiryDate: "有效期至", item: "项目", description: "描述", qty: "数量", price: "价格", total: "合计", subtotal: "小计", tax: "税", discount: "折扣", notes: "备注", termsAndConditions: "条款与条件", quotation: "报价单", invoice: "发票", customer: "客户", email: "邮箱", issue: "签发", due: "到期", expiry: "有效期", desc: "描述" },
  pricing: { title: "简单透明的定价", desc: "免费开始。随业务增长升级。无隐藏费用。", customPlan: "需要为您的团队定制计划？", contactUs: "联系我们" },
};

export default zh;
